//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Template_4337
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rabochie
    {
        public int ID { get; set; }
        public string PIO { get; set; }
        public string Login { get; set; }
        public Nullable<int> DolzhnostId { get; set; }
    
        public virtual Dolzhnosti Dolzhnosti { get; set; }
    }
}
